service: github-ci-cd-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  endpointType: regional

package:
  exclude:
    - node_modules/**

functions:
  functionOne:
    handler: lambda_fun.functionOne
    events:
      - http:
          path: /
          method: GET
          cors: true
    
