name: Node.js Install

on:
  push:
    branches:
      - master

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Installing depend... 
      run: npm install
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Serverless Deploy
      run: npm run-script deploy
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        body: |
          This is a multi-line test comment
        reactions: heart
